default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: engrave_adore_development

test:
  <<: *default
  database: engrave_adore_test

production:
  <<: *default
  database: engrave_adore_production